version: '3'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: deepsearch-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD:-yourpassword}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-yourpassword}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - deepsearch-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: deepsearch-redis-insight
    ports:
      - "8001:8001"
    volumes:
      - redis-insight-data:/db
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - deepsearch-network

volumes:
  redis-data:
    driver: local
  redis-insight-data:
    driver: local

networks:
  deepsearch-network:
    driver: bridge 